# Generated by Django 4.0.4 on 2022-04-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_item_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
    ]
