# Generated by Django 4.0.4 on 2022-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
