# Generated by Django 4.0.4 on 2022-04-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_item_edited_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at', '-edited_at']},
        ),
    ]
