# Generated by Django 4.0.4 on 2022-04-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at', 'edited_at']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
